Add workaround for compatibility with zope.i18nmessageid 7.0+ (Zope 5.11).
This would throw a TypeError in our `recursiveTranslate` function.
For now work around it: leave the recursive parts untranslated.

Sample test failure:

```
Error in test test_isDecimal (Products.validation.tests.test_validation.TestValidation.test_isDecimal)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.12.8/lib/python3.12/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.12.8/lib/python3.12/unittest/case.py", line 634, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.12.8/lib/python3.12/unittest/case.py", line 589, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/community/plone-coredev/6.0/src/Products.validation/Products/validation/tests/test_validation.py", line 62, in test_isDecimal
    v("NaN"), "Validation failed(isDecimal): 'NaN' is not a decimal number."
  File "/Users/maurits/community/plone-coredev/6.0/src/Products.validation/Products/validation/validators/RegexValidator.py", line 74, in __call__
    return recursiveTranslate(msg, **kwargs)
  File "/Users/maurits/community/plone-coredev/6.0/src/Products.validation/Products/validation/i18n.py", line 24, in recursiveTranslate
    map[key] = translate(map[key], context=request)
TypeError: 'mappingproxy' object does not support item assignment

```